### ISSUE TITLE
Feature Request: Is it possible to add support for LongPoll?

### ISSUE THREAD

**Issue by TiberiumN** [Fahreeve/aiovk#10]
https://vk.com/dev/using_longpoll может помочь при получении новых событий (добавили в друзья, написали в ЛС). Можно ли как-то реализовать это с помощью aiovk?

**Comment by Fahreeve** [comment]
почему закрыл?

**Comment by TiberiumPY** [comment]
Я у себя вот так сообщения получаю через long polling:
```python
result = await self.vk.method('messages.getLongPollServer', {'use_ssl': 1})
if not result:
    fatal('Не удалось подключиться к Long Poll серверу!')
self.longpoll_server = result['server']
self.longpoll_key = result['key']
self.last_ts = result['ts']
self.longpoll_values = {
    'act':'a_check',
    'key':self.longpoll_key,
    'ts':self.last_ts,
    'wait':1800,
    'mode':2,
    'version':1}
while True:
    async with aiohttp.ClientSession() as session:
        async with session.get("https://"+self.longpoll_server,
                                  params=self.longpoll_values) as resp:
            updates = await resp.json()
            # Обновляем время, чтобы не приходили старые события
            self.longpoll_values['ts'] = updates['ts']
            # Для каждого нового события
            for new_event in updates['updates']:
                # Если элемент массива пустой, идём к следующему
                if not new_event:
                    continue
                # Если событие - не новое сообщение
                 if not new_event[0]==4:
                    continue
                new_event = new_event[1:]
                msg_id,flags, peer_id, timestamp, subject, text, attaches = new_event
                print(peer_id)
```

**Comment by TiberiumPY** [comment]
@Fahreeve если хочешь, можешь по типу этого кода реализовать фичу

**Comment by Fahreeve** [comment]
сложно, надо будет сделать мне
думаю, что выглядеть будет так:
вызываешь метод, в ответ получает сессию сессию вставляешь в другой API объект и далее работаешь как обычно

было бы так удобно?

**Comment by TiberiumPY** [comment]
@Fahreeve ну покажи пример :)
Там как обычно не получится работать, там совсем другие типы полей.
Там нет JSON у событий, только массив
[Документация](https://vk.com/dev/using_longpoll?f=3.%20%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0%20%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B9)

**Comment by OlegWock** [comment]
Думаю, его стоит выполнить в виде такого-же запроса как и к обычному апи, просто при использовании тыкнул к нему await -- и прога уже не простаивает, а выполняет другие корутины. И линейная логика тогда не нарушается

**Comment by TiberiumPY** [comment]
@OlegWock у меня по сути тоже самое

**Comment by TiberiumPY** [comment]
@OlegWock просто это основано на HTTP запросах (постоянных)

**Comment by OlegWock** [comment]
@TiberiumPY да, я знаю. Просто @Fahreeve там что-то мудреное написал (так и не понял что), я предложил другой вариант. Можно, конечно, и калбэки прикрутить только это будет сложнее, и, как по мне, не нужно (когда уже те же Tornado&Twisted от них отказываются и переходят на futures)

**Comment by Fahreeve** [comment]
спасибо за предложения, глянул на документацию - то что я предлагал выше действительно не очень удобно

**Comment by TiberiumPY** [comment]
Можно использовать похожий API, как у vk_api:
https://github.com/python273/vk_api/blob/master/examples/longpoll.py

**Comment by Fahreeve** [comment]
добавил поддержку long poll

**Comment by TiberiumN** [comment]
@Fahreeve писать ботов для ВК станет ещё проще :)
