### ISSUE TITLE
Сервисный ключ доступа (будущее изменение в VK API)

### ISSUE THREAD

**Issue by Yardanico** [Fahreeve/aiovk#12]
https://vk.com/dev/service_token
В aiovk уже есть этот функционал? Если нет, можно ли его добавить?

**Comment by Fahreeve** [comment]
Если я правильно понял, то это особым образом сгенеренный токен. Попробуй использовать TokenSession

**Comment by TiberiumPY** [comment]
@Fahreeve пока этого нет в VK API, в апреле введут

**Comment by TiberiumPY** [comment]
@Fahreeve 
"Если в Вашем приложении используются открытые методы, необходимо изменить связанную с ними логику таким образом, чтобы в запросах передавался параметр access_token, содержащий сервисный ключ доступа. Получить или обновить его Вы можете в разделе редактирования Вашего приложения. "

**Comment by TiberiumPY** [comment]
@Fahreeve 
С апреля 2017 года для использования открытых методов и методов secure нужно будет использовать сервисный ключ доступа из настроек приложения. Вам не придется делать отдельный запрос к oauth.vk.com, чтобы получить его. Срок действия ключа не ограничен, но в любой момент Вы можете обновить его, при этом предыдущий ключ будет аннулирован.
