### ISSUE TITLE
Не работает api.execute(code="return 1;")

### ISSUE THREAD

**Issue by Nabu-thinker-ru** [Fahreeve/aiovk#18]
aiohttp.ClientSession.get  вызванный в drivers.py:76 нарезает параметр code в лапшу по точке с запятой. в результате VK возвращет ошибку 
`...'error_msg': "Unable to compile code:  ';' expected, '' found in line 1",...`

**Comment by Fahreeve** [comment]
Если пулл реквест сделаете сегодня обновлю. Иначе когда будет свободное время

**Comment by Fahreeve** [comment]
проблема все еще актуальна?

**Comment by Helow19274** [comment]
![default](https://user-images.githubusercontent.com/20171143/39625867-1eb378ce-4fa8-11e8-9c3b-8265af13834d.png)
Всё работает нормально
