### ISSUE TITLE
user should have way to choose backend [feature-request]

### ISSUE THREAD

**Issue by pohmelie** [Fahreeve/aiovk#2]
It's better to give user way to choose http backend on session create. Probably this should be oriented on requests/aiohttp api, since they are pretty common. So, the way is like user create session with proxy/optoins and pass it to the library. You can take a look at https://github.com/pohmelie/aiotelegram and `json_provider` it's a bit like what you need to be independent of http libraries api.

**Comment by Fahreeve** [comment]
added in 0.3 version
