### ISSUE TITLE
Нерабочий пример

### ISSUE THREAD

**Issue by ZSides** [Fahreeve/aiovk#25]
Привет! Боюсь показаться глупым, но у меня ничего не получается уже весь день :(
Беру код из примера. Он же работал у меня пару месяцев назад
```
async def func():
    session = aiovk.ImplicitSession(vk_login, vk_pass, APP_ID, 'video,offline')
    await session.authorize()
    print(session.access_token)
    session.close()
loop = asyncio.get_event_loop()
loop.run_until_complete(func())
```
и получаю кучу ошибок и не знаю что с этим делать
На строку с `session.close()` ругается "`RuntimeWarning: coroutine 'BaseSession.close' was never awaited`"
Зачем-то написал `await session.close()` (потому что session.close is now awaitable) - не помогло.
Причем токен-то выводит принтом
Еще я узнаю что я:
`session.close()
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x066E62F0>
ERROR:asyncio:Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x069CCEF0>, 228423.625)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x05A0CB70>, 228423.64)]']
connector: <aiohttp.connector.TCPConnector object at 0x066E6310>
`
Попробовал еще сделать `async with aiovk.TokenSession(access_token=token) as ses:` но он вообще говорит, что не ожидал увидеть тут `async`.
Заранее прошу прощения за глупые вопросы и ваше потраченное время, я только учусь

**Comment by Fahreeve** [comment]
Вопросы заданы верные readme я забыл обновить так что вместо `session.close()` действительно должен быть `await session.close()`
С `async with` не могу сходу подсказать.
Можешь ещё в тесты глянуть, мб там найдешь что полезное

**Comment by ZSides** [comment]
Да если добавить await перед close, то есть код выглядит вот так:
`async def f():
    session = aiovk.ImplicitSession('+71112223344','parol', 1234, scope='video,offline')
    await session.authorize()
    api = aiovk.API(session)
    await session.close()
loop = asyncio.get_event_loop()
loop.run_until_complete(f())`
то падает с 
`Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x068E62B0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x06BCCF70>, 237739.953)]', '[(<aiohttp.client_proto.ResponseHandler object at 0x05C1CBD0>, 237739.968)]']
connector: <aiohttp.connector.TCPConnector object at 0x068E62D0>`

**Comment by Fahreeve** [comment]
`await session.authorize()` убери, он не нужен. Этот метод вызывается внутри API. А `Unclosed client session` должно быть ворнингом по идее
