### ISSUE TITLE
Long Poll

### ISSUE THREAD

**Issue by DjHaski** [Fahreeve/aiovk#34]
Бот с Bots Long Poll не принимает сообщения из чатов, в которые он был приглашен. Только через упоминание (@) и сообщения сообщества. Права выданы, все настроено.

Каким образом получать сообщения? Не понятно.

**Comment by Fahreeve** [comment]
ничего не могу подсказать. В телеграме, например, боты не могут читать все сообщения

**Comment by DjHaski** [comment]
Да в телеге я как рыба плаваю, вопросов никаких вообще не возникает. Этот ВК уже заманал, ничего не понятно.

Ладно, буду пробовать, искать, ппц...
