### ISSUE TITLE
Добавить ограничение запросов в секунду

### ISSUE THREAD

**Issue by TiberiumPY** [Fahreeve/aiovk#4]
Нужно добавить ограничение на кол-во запросов в секунду (~3 запроса).
Так будет проще делать сложные боты для VK

**Comment by Fahreeve** [comment]
1) не всем нужны такие ограничения
2) я считаю, что следить за количеством запросов в секунду вы должны сами

**Comment by TiberiumPY** [comment]
@Fahreeve сделай это дополнительным аргументом при создании TokenSession.
У меня, например, сложный бот для ВК, и
            await asyncio.sleep(0.34)  # 3 запроса  в секунду
            await self.check_messages()
мне не помогает (когда одновременно много людей пишут)

**Comment by Fahreeve** [comment]
у меня нет идей как это реализовать в TokenSession
Могу предложить сделать тебе асинхронную очередь, а в ней переопределить методы pop и put чтобы за секунду они не отдавали больше 3 команд для запросов

**Comment by TiberiumPY** [comment]
@Fahreeve у pohmelie есть "грязная" реализация трёх запросов в секунду

**Comment by Fahreeve** [comment]
нет, я все таки так делать не буду, я предоставляю только обертку над АПИ, за временем следи сам

**Comment by TiberiumPY** [comment]
@Fahreeve мдя... притом эта функция есть и в vk, и в vk_api

**Comment by mefuckin** [comment]
Написал для себя обёртку над aiovk.API, ограничивающую количество запросов в секунду. Может, пригодится
```
from time import time
import asyncio

import aiovk


class API(object):
    """Enqueue VK API requests and limit rate to 3 requests per second."""

    def __init__(self, *args, **kwargs):
        self._api = aiovk.API(*args, **kwargs)
        self._q = asyncio.Queue()
        self.last_time = 0
        asyncio.ensure_future(self.dispatcher())

    async def __call__(self, *args, **kwargs):
        fut = asyncio.Future()
        coro = self._api(*args, **kwargs)
        await self._q.put((coro, fut))
        return await fut

    async def dispatcher(self):
        c = 0
        while True:
            coro, fut = await self._q.get()
            if c >= 3:
                if time() - self.last_time <= 1:
                    await asyncio.sleep(1.1)
                c = 0
            r = await coro
            fut.set_result(r)
            self.last_time = time()
            c += 1


async def test():
    api = API(aiovk.TokenSession())

    async def f():
        r = await api("utils.getServerTime")
        print(r)

    await asyncio.wait([f() for i in range(50)])


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(test())
```

**Comment by Fahreeve** [comment]
ок, раз мне даже код предоставили то попробую реализовать
Думаю, что в библиотеку добавлю Mixin для драйвера, т.е вам надо будет делать что-то вроде этого:
```
class Driver(LimitMixin, HttpDriver):
    pass

session = TokenSession(..., driver=Driver())
```
Вам будет удобно так пользоваться?

**Comment by TiberiumPY** [comment]
@Fahreeve да

**Comment by Fahreeve** [comment]
@mefuckin, я так понял, что твой код делает НЕ БОЛЬШЕ 3 запросов, т.е при медленном соединении он будет ждать когда какой-то из запросов закончится

**Comment by mefuckin** [comment]
@Fahreeve, угу, запросы выполняются последовательно (следующий не начнётся, пока не закончится предыдущий), после каждого 3-го запроса проверяется время, прошедшее со времени последнего запроса. Ещё в приведённом коде недостаток в том, что если какой-то один запрос бросит исключение, упадёт весь диспетчер

**Comment by TiberiumPY** [comment]
@mefuckin это для меня очень плохо :( Я просто бота для ВК пишу, и иногда может быть ошибка - одинаковое сообщение, и у меня раньше для этого отлавливалась ошибка, и посылалось сообщение с рандомными символами

**Comment by Fahreeve** [comment]
я работаю над этим уже, ждите

**Comment by TiberiumPY** [comment]
@Fahreeve супер! Я наконец-то смогу сконцентрироваться на улучшении самого бота, а не отслежкой кол-ва запросов в секунду :)

**Comment by TiberiumPY** [comment]
@Fahreeve уж тогда делай сразу 0.4

**Comment by Fahreeve** [comment]
как по английски особенность, что либа позволяет контролировать кол-во запросов в секунду?

**Comment by Fahreeve** [comment]
0ffa8f9 Добавил ограничение кол-во запросов в секунду -  проверяйте

**Comment by TiberiumPY** [comment]
@Fahreeve 
  File "/home/tiber/.local/lib/python3.5/site-packages/aiovk/utils.py", line 27, in wrapper
    await self._queue.get()
AttributeError: 'str' object has no attribute '_queue'

**Comment by TiberiumPY** [comment]
@Fahreeve 
`  File "/home/tiber/.local/lib/python3.5/site-packages/aiovk/api.py", line 9, in __call__
    return await getattr(self, method_name)(**method_kwargs)
  File "/home/tiber/.local/lib/python3.5/site-packages/aiovk/api.py", line 25, in __call__
    return await self._api._session.make_request(self, timeout)
  File "/home/tiber/.local/lib/python3.5/site-packages/aiovk/sessions.py", line 24, in make_request
    return await self.send_api_request(method_request._method_name, params, timeout)
  File "/home/tiber/.local/lib/python3.5/site-packages/aiovk/sessions.py", line 34, in send_api_request
    response = await self.driver.json(self.REQUEST_URL + method_name, params, timeout)
  File "/home/tiber/.local/lib/python3.5/site-packages/aiovk/utils.py", line 27, in wrapper
    await self._queue.get()
AttributeError: 'str' object has no attribute '_queue'
`

**Comment by TiberiumPY** [comment]
@Fahreeve 
http://stackoverflow.com/questions/11731136/python-class-method-decorator-w-self-arguments

**Comment by TiberiumPY** [comment]
@Fahreeve декоратор применяется к объекту класса ДО его инициализации

**Comment by Fahreeve** [comment]
я вообще не понимаю, почему именно эта ошибка возникает `AttributeError: 'str' object has no attribute '_queue'`

**Comment by TiberiumPY** [comment]
@Fahreeve потому что self - строка

**Comment by TiberiumPY** [comment]
@Fahreeve т.к. self не передаётся декоратору вроде как

**Comment by TiberiumPY** [comment]
@Fahreeve что ты имел ввиду под self._queue.get() ???

**Comment by Fahreeve** [comment]
почему у меня тогда тесты проходят на ок?

**Comment by TiberiumPY** [comment]
@Fahreeve попробуй сделай сам простой пример, а не тесты

**Comment by TiberiumPY** [comment]
@Fahreeve что ты имел ввиду под self._queue.get() ???

**Comment by TiberiumPY** [comment]
@Fahreeve _queue - аттрибут asyncio.Queue класса, и это объект collections.deque, у которого нет метода get

**Comment by Fahreeve** [comment]
не путай, есть _queue, который в миксине, а есть который внутр TaskQueue (тут он как раз collections.deque), а в asyncio.Queue есть метод get

**Comment by TiberiumPY** [comment]
@Fahreeve ну попробуй сделать пример с доступом к VK API, ты лучше понимаешь структуру своей библиотеки

**Comment by Fahreeve** [comment]
да че за фигня, у меня все норм работает

**Comment by TiberiumPY** [comment]
@Fahreeve у меня Python 3.5.2

**Comment by Fahreeve** [comment]
у меня тоже

**Comment by Fahreeve** [comment]
```python
import asyncio

from aiovk import API
from aiovk import ImplicitSession
from aiovk.drivers import HttpDriver
from aiovk.mixins import LimitRateDriverMixin
from tests.auth_data import USER_LOGIN, USER_PASSWORD, APP_ID


class ExampleDriver(LimitRateDriverMixin, HttpDriver):
    requests_per_period = 3
    period = 1  #seconds

async def test():
    session = ImplicitSession(USER_LOGIN, USER_PASSWORD, APP_ID, driver=ExampleDriver())
    api = API(session)
    a = await api.users.get(user_ids=1)
    return a

loop = asyncio.get_event_loop()
loop.run_until_complete(test())
```
у тебя такой код?

**Comment by TiberiumPY** [comment]
@Fahreeve бл*ть...Я тупанул) не написал скобки, которые инициализируют класс ExampleDriver()

**Comment by TiberiumPY** [comment]
@Fahreeve Всё работает, правда я период повыше поставил  (1.15)

**Comment by Fahreeve** [comment]
@TiberiumPY как мне назвать эту фичу по английски?

**Comment by TiberiumPY** [comment]
@Fahreeve Rate limit?

**Comment by TiberiumPY** [comment]
@Fahreeve огромное спасибо, всё теперь работает!

**Comment by TiberiumPY** [comment]
@Fahreeve и ошибки даже фиксируются

**Comment by mefuckin** [comment]
У меня не работает.
```
import asyncio

from aiovk import API
from aiovk import TokenSession
from aiovk.drivers import HttpDriver
from aiovk.mixins import LimitRateDriverMixin

class ExampleDriver(LimitRateDriverMixin, HttpDriver):
    requests_per_period = 3
    period = 1

async def test():
    session = TokenSession(driver=ExampleDriver())
    api = API(session)

    async def f():
        a = await api.utils.getServerTime()
        print(a)

    await asyncio.wait([f() for i in range(50)])

loop = asyncio.get_event_loop()
loop.run_until_complete(test())
```
Если запустить, то видно, что все 50 запросов выполняются сразу. ЧЯДНТ?

**Comment by TiberiumPY** [comment]
@mefuckin у меня всё норм

**Comment by TiberiumPY** [comment]
@Fahreeve ошибка правда, даже в том коде, который показал @mefuckin :
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f8375732588>
Task was destroyed but it is pending!
task: <Task pending coro=<TaskQueue.dispatcher() running at /home/tiber/bench/aiovk/aiovk/utils.py:17> wait_for=<Future pending cb=[Task._wakeup()]>>

**Comment by Fahreeve** [comment]
`
Unclosed client session
client_session: aiohttp.client.ClientSession object at 0x7f8375732588
Task was destroyed but it is pending!
task: Task pending coro=TaskQueue.dispatcher() running at /home/tiber/bench/aiovk/aiovk/utils.py:17 wait_for=Future pending cb=[Task._wakeup()]
`
это warning, в этом коде я не закрываю сессию, а надо бы `session.close()`
по хорошему, в моем примере надо было сессию и апи вынести из функции, но мне было лень)

**Comment by Fahreeve** [comment]
@mefuckin, да, все правильно, должны там быть все 50 корутин выполнятся, но реальных запросов делается всего 3, потому что все остальные спят

**Comment by mefuckin** [comment]
Не, у меня там именно все 50 выполнялись сразу. Что это за версия 0.3.3 была? На момент того коммента она лежала в pypi и в ней новый миксин присутствовал, но не работал корректно. Сейчас обновил до 0.4, всё работает как надо - пауза после каждый трёх запросов. Спасибо!
