### ISSUE TITLE
Exception aiohttp.client_exceptions.InvalidURL when token is expired

### ISSUE THREAD

**Issue by alexanderlarin** [Fahreeve/aiovk#42]
Hi!

Something strange happen when ImplicitSession tried to re-authorize
I used phone/password credentials and  auth url is empty in this case

The stack is:
 Traceback (most recent call last):
  File "/home/user/bot/bot.py", line 197, in watch_update_posts
    await walk_wall_posts(api, store, owner_id, max_posts_offset=30)
  File "/home/user/bot/vk.py", line 41, in walk_wall_posts
    items, count = await get_wall_posts(api, owner_id=owner_id, offset=offset, limit=posts_per_request_limit)
  File "/home/user/venv/lib/python3.7/site-packages/backoff/_async.py", line 131, in retry
    ret = await target(*args, **kwargs)
  File "/home/user/bot/vk.py", line 29, in get_wall_posts
    response = await api.wall.get(owner_id=owner_id, offset=offset, count=limit, extended=0, filter='all')
  File "/home/user/venv/lib/python3.7/site-packages/aiovk/api.py", line 31, in __call__
    timeout,
  File "/home/user/venv/lib/python3.7/site-packages/aiovk/sessions.py", line 90, in send_api_request
    await self.authorize()
  File "/home/user/venv/lib/python3.7/site-packages/aiovk/sessions.py", line 154, in authorize
    url, html = await self._process_auth_form(html)
  File "/home/user/venv/lib/python3.7/site-packages/aiovk/sessions.py", line 224, in _process_auth_form
    url, html = await self.driver.post_text(form_url, form_data)
  File "/home/user/venv/lib/python3.7/site-packages/aiovk/drivers.py", line 69, in post_text
    async with self.session.post(url, data=data, timeout=timeout or self.timeout) as response:
  File "/home/user/venv/lib/python3.7/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/home/user/venv/lib/python3.7/site-packages/aiohttp/client.py", line 466, in _request
    ssl=ssl, proxy_headers=proxy_headers, traces=traces)
  File "/home/user/venv/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 286, in __init__
    self.update_host(url)
  File "/home/user/venv/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 340, in update_host
    raise InvalidURL(url)
aiohttp.client_exceptions.InvalidURL

**Comment by Fahreeve** [comment]
Hi, I don’t have time to debug at the moment
I will be happy to get a PR with a patch

**Comment by alexanderlarin** [comment]
I could try to do something with that. I think it's not so difficult, but could you please give me some explanation for authorize function pipeline. It has too many different cases for auth form url

**Comment by Fahreeve** [comment]
the order is described [here](https://github.com/Fahreeve/aiovk/blob/85098d195e4836858856416258ea3249c5c9e95b/aiovk/sessions.py#L151)

also i think you need put a breakpoint [here](https://github.com/Fahreeve/aiovk/blob/85098d195e4836858856416258ea3249c5c9e95b/aiovk/sessions.py#L224) and see the value of variable `html` and `form_url`

**Comment by alexanderlarin** [comment]
Hi, I investigated the problem
If we use implicit session flow, and our access_token expires in 24 hours then send_api_request will get authorization error and will try to re-authorize. In this case if have the SAME aiohttp session object as in previous authorization, get request for auth url https://oauth.vk.com/authorize will be redirected to /blank.html immediately without re-entering login and password.
This page doesn't contain any form fields and causes to parsing error.
There are 2 problems, I think
1. We have no method that validates parser results (two factored, auth etc.) and sometimes it leads to raising exceptions that are not related to what is really happening (as in case of InvalidURL exception in the issue).
2 [Here](https://github.com/Fahreeve/aiovk/blob/85098d195e4836858856416258ea3249c5c9e95b/aiovk/sessions.py#L149) we could be redirected to blank.html page and got access_token if we use already authorized session. [This method](https://github.com/Fahreeve/aiovk/blob/85098d195e4836858856416258ea3249c5c9e95b/aiovk/sessions.py#L171) should return url from [this method](https://github.com/Fahreeve/aiovk/blob/85098d195e4836858856416258ea3249c5c9e95b/aiovk/drivers.py#L29). But I can't add additional argument that contains response.real_url resut because HttpDriver is customizable and I will break back-compatibility

What should I do in this case?

**Comment by alexanderlarin** [comment]
See the python code sample below:
```
import asyncio
import aiovk

if __name__ == '__main__':
    async def loop():
        async with aiovk.ImplicitSession(...) as session:
			await session.authorize()  # First requires login/password
			await session.authorize()  # Second redirects straigth to blank.html page

    asyncio.get_event_loop().run_until_complete(loop())
```
