### ISSUE TITLE
Incorrect handling of 414 http error

### ISSUE THREAD

**Issue by DjHaski** [Fahreeve/aiovk#44]
If we send api request, we can catch strange error:

```aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url='*long url*'```

I found out, it was caused by an http error  `414 Request-URI Too Long`. There already was issue about this error (#41), but I think proper solution is to raise VkAPIError somewhere. I don't really know where to put it, that's why I can't just create PR. Any help?

**Comment by Fahreeve** [comment]
Привет, эта ошибка возникает уже не в первый раз, но до сих пор никто мне не прислал урла на котором это произошло. 
Я думаю, что стоит задебажить эту [строчку](https://github.com/Fahreeve/aiovk/blob/master/aiovk/api.py#L28) чтобы понять в чем причина. Возможно в какой-то момент отправляется GET запрос вместо POST

**Comment by DjHaski** [comment]
В общем, у ВК похоже, есть ограничение на длину урлы. У меня лично это произошло при использовании метода `messages.send`. Наверное потому, что сообщение было слишком длинное. Метод, в котором произошла ошибка: `HttpDriver.json`, в нем используется `self.session.get` (GET Запрос). Сервак возвращает страницу nginx `414 Request-URI Too Long` и все. Метод же, не имея обработчика 414 статус кода, просто пытается вытащить JSON, что, конечно же, у него и не получается.

**Comment by Fahreeve** [comment]
хм, попробуй вместо GET запроса POST отправить, я думаю это должно помочь.
Для простоты эксперимента кмк достаточно будет [тут](https://github.com/Fahreeve/aiovk/blob/master/aiovk/drivers.py#L57) поменять гет на пост

**Comment by DjHaski** [comment]
Ничего не изменилось, все та же ошибка 414.

**Comment by Fahreeve** [comment]
а в самом урле что занимает большую его часть? данные?

**Comment by DjHaski** [comment]
Поле `message`

**Comment by Fahreeve** [comment]
не, тебе надо было все query params урла закинуть в тело запроса. А в урле оставить только messages.send

**Comment by DjHaski** [comment]
Во! Заработало, никаких ошибок.

**Comment by Fahreeve** [comment]
теперь остается придумать общее решение для подобных проблем

**Comment by Fahreeve** [comment]
если оставить все как я тебе сказал, то остальные запросы норм отрабатывают?

**Comment by DjHaski** [comment]
Другие методы не тестировал. Но думаю, если `messages.send` работает, то почему другие не будут?

**Comment by Fahreeve** [comment]
присылай пулл реквест тогда

**Comment by Fahreeve** [comment]
и я его сегодня соберу вместе с другим PR

**Comment by Fahreeve** [comment]
затести ветку v4

**Comment by Fahreeve** [comment]
у меня не падают, не смог воспроизвести

**Comment by DjHaski** [comment]
Все в порядке, не падает ничего, я накосячил.
