### ISSUE TITLE
Error in  aiovk/sessions.py with messages.get method

### ISSUE THREAD

**Issue by TiberiumPY** [Fahreeve/aiovk#6]
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/tiber/LOLBot/vkplus.py", line 85, in dispatcher
    r = await coro
  File "/usr/local/lib/python3.5/dist-packages/aiovk-0.3.3-py3.5.egg/aiovk/api.py", line 9, in __call__
    return await getattr(self, method_name)(**method_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/aiovk-0.3.3-py3.5.egg/aiovk/api.py", line 25, in __call__
    return await self._api._session.make_request(self, timeout)
  File "/usr/local/lib/python3.5/dist-packages/aiovk-0.3.3-py3.5.egg/aiovk/sessions.py", line 24, in make_request
    return await self.send_api_request(method_request._method_name, params, timeout)
  File "/usr/local/lib/python3.5/dist-packages/aiovk-0.3.3-py3.5.egg/aiovk/sessions.py", line 52, in send_api_request
    return response['response']
KeyError: 'response'

Параметры, с которыми вызывалась функция:
METHOD messages.get
PARAMS {'access_token': '608a2afedc7e06346***84b3ec9bc5c719eb961961133804a9404526084903aaaea1300c29fcacb574051', 'filters': 0, 'last_message_id': 0, 'time_offset': 60, 'out': 0, 'v': '5.52', 'offset': 0, 'count': 20, 'preview_length': 0}

В response было {'items': [], 'count': 28205}

**Comment by TiberiumPY** [comment]
Можно сделать:
```python
try:
    return response['response']
except KeyError:
    return response

```

**Comment by Fahreeve** [comment]
тогда уж, надо юзать response.get()
я у себя затестил, у меня все работает
значит от тебя нужно больше инфы

**Comment by TiberiumPY** [comment]
@Fahreeve попробуй несколько раз

**Comment by TiberiumPY** [comment]
{'count': 20, 'preview_length': 0, 'filters': 0, 'out': 0, 'time_offset': 60, 'last_message_id': 0, 'offset': 0}
С этими параметрами

**Comment by Fahreeve** [comment]
10 раз попробовал у меня выводит только это `{'items': [], 'count': 28205}`

**Comment by TiberiumPY** [comment]
@Fahreeve Ну вот

**Comment by TiberiumPY** [comment]
@Fahreeve А у тебя в коде return response['response'], и , как ты видишь, в этом словаре нет response

**Comment by Fahreeve** [comment]
дык это и есть содержание response из ответа сервера
ВК возвращает json приблизительно такого содержания {'response': {}, 'errors': {}}

**Comment by TiberiumPY** [comment]
@Fahreeve ну скажи, какую ещё инфу выводить.

**Comment by TiberiumPY** [comment]
А, ща, посмотрю кое-что

**Comment by TiberiumPY** [comment]
@Fahreeve с response.get('response',response) всё работает

**Comment by Fahreeve** [comment]
а ты куда это `response.get('response',response)` поставил?

**Comment by TiberiumPY** [comment]
@Fahreeve где return response['response'] заменил на return response.get('response',response)

**Comment by Fahreeve** [comment]
ну это странно на самом деле, вк раньше выдавал словарь {'response': {...}} не верю, что они там что-то изменили, покажи тогда всю структуру сообщений когда есть response внутри и когда нет его

**Comment by TiberiumPY** [comment]
@Fahreeve он только один(!) раз возвращает JSON без response

**Comment by TiberiumPY** [comment]
@Fahreeve вот тут возвращается без response:
            elif err_code == AUTHORIZATION_FAILED:
                await self.authorize()
                response = await self.send_api_request(method_name, params, timeout)
                print(response)
Это происходит из за того, что вызывается тот же метод, а методом send_api_request возвращается response['response']

**Comment by TiberiumPY** [comment]
@Fahreeve как вариант сделать так:
```python
            elif err_code == AUTHORIZATION_FAILED:
                await self.authorize()
                response = {'response':await self.send_api_request(method_name, params, timeout)}
```
Тогда всё работает

**Comment by TiberiumPY** [comment]
Весёлый баг однако :)

**Comment by Fahreeve** [comment]
да, кажется это действительно он, попробуй еще так:
```python
     params['captcha_sid'] = captcha_sid
     return await self.send_api_request(method_name, params, timeout)
elif err_code == AUTHORIZATION_FAILED:
     await self.authorize()
     return await self.send_api_request(method_name, params, timeout)
```
там на return заменил

**Comment by TiberiumPY** [comment]
@Fahreeve так тоже работает, можешь фиксить и закрывать тикет
