### ISSUE TITLE
Unclosed client session.

### ISSUE THREAD

**Issue by nxbx** [Fahreeve/aiovk#9]
После каждого запроса получаю:
```
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f705e376390>
```
Как можно закрыть aiohttp сессию?

**Comment by Fahreeve** [comment]
вот пример использования, не забывай вызывать метод close у сессии
```python
import asyncio

from aiovk import API
from aiovk import ImplicitSession
from aiovk.drivers import HttpDriver
from aiovk.mixins import LimitRateDriverMixin
from tests.auth_data import USER_LOGIN, USER_PASSWORD, APP_ID


class ExampleDriver(LimitRateDriverMixin, HttpDriver):
    requests_per_period = 3
    period = 1  #seconds

async def test():
    session = ImplicitSession(USER_LOGIN, USER_PASSWORD, APP_ID, driver=ExampleDriver())
    api = API(session)
    a = await api.users.get(user_ids=1)
    session.close()
    return a

loop = asyncio.get_event_loop()
loop.run_until_complete(test())
```

**Comment by TiberiumPY** [comment]
Я у себя никак не смогу его вызвать :)
Ну если это не страшно, то пофиг

**Comment by TiberiumPY** [comment]
У меня очень страшная структура бота

**Comment by Fahreeve** [comment]
это не страшно

**Comment by TiberiumPY** [comment]
@Fahreeve у меня просто код вперемешку

**Comment by Fahreeve** [comment]
Инициализация сессии не содержит в себе асинхронных элементов, так что можешь создавать переменную с ней глобально, и где-то в какой-то функции закрывать сессию

**Comment by TiberiumPY** [comment]
@Fahreeve ок

**Comment by TiberiumPY** [comment]
@Fahreeve сессию закрывать при выключении программы же только?

**Comment by Fahreeve** [comment]
если ты работаешь с одним аккаунтом, то точно да

**Comment by nxbx** [comment]
Большое спасибо! )
А если внутри будет два запроса к api, то когда закрывать сессию?
После каждого запроса, или в конце перед:
```
loop = asyncio.get_event_loop()
loop.run_until_complete(test())
```
Сейчас пробую, но начал вылетать с ошибкой  
`RuntimeError: Session is closed`

**Comment by TiberiumPY** [comment]
@nxbx значит ты до конца самой программы закрываешь сессию

**Comment by TiberiumPY** [comment]
@Fahreeve всё работает, спасибо

**Comment by Fahreeve** [comment]
@nxbx я  выше тебе код прислал, можешь ставь закрытие сессии до return, но после всех запросов

**Comment by TiberiumPY** [comment]
@Fahreeve оказалось очень просто сделать :)
https://github.com/TiberiumPY/LOLBot/commit/b0a400349987aa17e3b29fba966707b0a8d3f6d2

**Comment by nxbx** [comment]
@Fahreeve за код отдельное спасибо! Разобрался.
Может добавить session.close() в примеры к либе?)

**Comment by Fahreeve** [comment]
надо бы, я это сделаю когда-нибудь:)

**Comment by Deathik** [comment]
Есть идея добавить такой код к TokenSession:
```
    async def __aenter__(self):
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        self.close()
```
Таким образом можно будет использовать конструкцию 
```
async with aiovk.TokenSession(access_token=VK_TOKEN) as ses:
 ...code...
```
И не нужно будет делать .close() вручную

**Comment by Fahreeve** [comment]
@Deathik, а давай)
С тебя пулреквест, не забудь в README в разделе Authorization добавить инфу про эту фичу
